### PR TITLE
Small fixes

### LINKED ISSUE #15: UI: Add "target" timeout in printout
On long TCP timeouts it would be good to know what is the expected time you will get the response from the server. 
I.e. "Elapsed time : 50422 of 64334 seconds" or something similar.

### LINKED ISSUE #17: After timeout firmware keeps sending on closed connection
If the server encounters a TCP timeout, it will close the connection.
However the device seems to keep sending on this connection, but the server does not receive the messages, so in this case the devices starts the binary search and finally reports the TCP timeout with 0, because the server never replies.

```
13:15:07 [0a163c9d-10ac-43af-89b7-29417b179bd0] TCP write to 193.181.245.204:40159 failed. Connection terminated. Interval: 300.
```

```
[2020-05-18 15:10:06] [00:01:11.717,498] <dbg> lte_lc.parse_nw_reg_status: Network registration status: 5
[2020-05-18 15:10:06] Connected to server with protocol TCP
[2020-05-18 15:10:06] Packet sent: {
[2020-05-18 15:10:06]   "ip":   ["10.81.175.204"],
[2020-05-18 15:10:06]   "op":   "24202",
[2020-05-18 15:10:06]   "cell_id":      34247436,
[2020-05-18 15:10:06]   "ue_mode":      2,
[2020-05-18 15:10:06]   "lte_mode":     1,
[2020-05-18 15:10:06]   "nbiot_mode":   0,
[2020-05-18 15:10:06]   "iccid":        "89450421180216254864",
[2020-05-18 15:10:06]   "imei": "352656100378903",
[2020-05-18 15:10:06]   "interval":     300
[2020-05-18 15:10:06] }
[2020-05-18 15:10:06] Waiting for response...
[2020-05-18 15:11:06] Elapsed time: 60 seconds
[2020-05-18 15:12:06] Elapsed time: 120 seconds
[2020-05-18 15:13:06] Elapsed time: 180 seconds
[2020-05-18 15:14:06] Elapsed time: 240 seconds
[2020-05-18 15:15:06] Elapsed time: 300 seconds
[2020-05-18 15:16:06] No response from server
[2020-05-18 15:16:07] Packet sent: {
[2020-05-18 15:16:07]   "ip":   ["10.81.175.204"],
[2020-05-18 15:16:07]   "op":   "24202",
[2020-05-18 15:16:07]   "cell_id":      34247436,
[2020-05-18 15:16:07]   "ue_mode":      2,
[2020-05-18 15:16:07]   "lte_mode":     1,
[2020-05-18 15:16:07]   "nbiot_mode":   0,
[2020-05-18 15:16:07]   "iccid":        "89450421180216254864",
[2020-05-18 15:16:07]   "imei": "352656100378903",
[2020-05-18 15:16:07]   "interval":     150
[2020-05-18 15:16:07] }
[2020-05-18 15:16:07] Waiting for response...
[2020-05-18 15:17:07] Elapsed time: 60 seconds
[2020-05-18 15:18:07] Elapsed time: 120 seconds
[2020-05-18 15:19:07] No response from server
[2020-05-18 15:19:07] Packet sent: {
[2020-05-18 15:19:07]   "ip":   ["10.81.175.204"],
[2020-05-18 15:19:07]   "op":   "24202",
[2020-05-18 15:19:07]   "cell_id":      34247436,
[2020-05-18 15:19:07]   "ue_mode":      2,
[2020-05-18 15:19:07]   "lte_mode":     1,
[2020-05-18 15:19:07]   "nbiot_mode":   0,
[2020-05-18 15:19:07]   "iccid":        "89450421180216254864",
[2020-05-18 15:19:07]   "imei": "352656100378903",
[2020-05-18 15:19:07]   "interval":     75
[2020-05-18 15:19:07] }
[2020-05-18 15:19:07] Waiting for response...
[2020-05-18 15:20:07] Elapsed time: 60 seconds
[2020-05-18 15:21:07] No response from server
[2020-05-18 15:21:07] Packet sent: {
[2020-05-18 15:21:07]   "ip":   ["10.81.175.204"],
```

### LINKED ISSUE #18: Reset power saving settings in modem before running tests
Settings like eDRX are preserved in the modem flash and might be present from a previous app run. These need to be reset before running the tests.

@jtguggedal will provide the AT commands to achieve this.

### PR DESCRIPTION
**Pull request by boundlesscalm**
Unsure about the branch name/squashed commit message.
I felt as if these commits were similar enough in objective and small enough to fit into a single commit, though feel free to let me know if this should be changed.

### CODE REVIEW

**Comment by coderbyheart** [comment]
**In the future** please use separate PRs, especially if there are already existing issue. It makes it easier for reviewers to understand which change addresses which issue, without needing to go through the commits.

**Comment by coderbyheart** [comment]
How is #14 addressed in this PR?

**Comment by boundlesscalm** [comment]
That commit was accidentally not added to this pr. Would you prefer it in a different commit or to add it?

**Comment by coderbyheart** [comment]
Yes.

**Comment by coderbyheart** [comment]
> Would you prefer it in a different commit or to add it?

Yes.

**Comment by coderbyheart** [comment]
> Would you prefer it in a different commit or to add it?

Please use a separate PR for the reasons stated above.

**Review by jhn-nordic — APPROVED** [review]

**Pull request merged**
