### PR TITLE
feat: Add use of leds to show state of test

### LINKED ISSUE #14: LED Feedback
Blink one LED during tests.

Blink LED 1-4 in rotation once all tests are done to see that the DK can be turned of or resetted for a new test.

### PR DESCRIPTION
**Pull request by boundlesscalm**
Signed-off-by: Pascal Pickel <Pascal.Pickel@nordicsemi.no>

### CODE REVIEW

**Comment by coderbyheart** [comment]
Can you attach a FW build so I can test it?

**Review by coderbyheart — CHANGES_REQUESTED** [review]
Please document in the source (or in the README) what the LEDs are supposed to be doing.

**Comment by PascalPickel** [comment]
[merged.zip](https://github.com/NordicSemiconductor/NAT-TestFirmware/files/4786315/merged.zip)

**Comment by coderbyheart** [comment]
> [merged.zip](https://github.com/NordicSemiconductor/NAT-TestFirmware/files/4786315/merged.zip)

This one boots to uart shell and does nothing.

```
*** Booting Zephyr OS build v2.1.99-ncs1-2956-g9bab3a84b642  ***
Flash regions           Domain          Permissions
00 00 0x00000 0x08000   Secure          rwxl
01 31 0x08000 0x100000  Non-Secure      rwxl

Non-secure callable region 0 placed in flash region 0 with size 32.

SRAM region             Domain          Permissions
00 07 0x00000 0x10000   Secure          rwxl
08 31 0x10000 0x40000   Non-Secure      rwxl

Peripheral              Domain          Status
00 NRF_P0               Non-Secure      OK
01 NRF_CLOCK            Non-Secure      OK
02 NRF_RTC0             Non-Secure      OK
03 NRF_RTC1             Non-Secure      OK
04 NRF_NVMC             Non-Secure      OK
05 NRF_UARTE1           Non-Secure      OK
06 NRF_UARTE2           Secure          SKIP
07 NRF_TWIM2            Non-Secure      OK
08 NRF_SPIM3            Non-Secure      OK
09 NRF_TIMER0           Non-Secure      OK
10 NRF_TIMER1           Non-Secure      OK
11 NRF_TIMER2           Non-Secure      OK
12 NRF_SAADC            Non-Secure      OK
13 NRF_PWM0             Non-Secure      OK
14 NRF_PWM1             Non-Secure      OK
15 NRF_PWM2             Non-Secure      OK
16 NRF_PWM3             Non-Secure      OK
17 NRF_WDT              Non-Secure      OK
18 NRF_IPC              Non-Secure      OK
19 NRF_VMC              Non-Secure      OK
20 NRF_FPU              Non-Secure      OK
21 NRF_EGU1             Non-Secure      OK
22 NRF_EGU2             Non-Secure      OK
23 NRF_DPPIC            Non-Secure      OK
24 NRF_GPIOTE1          Non-Secure      OK
25 NRF_REGULATORS       Non-Secure      OK

SPM: NS image at 0xc000
SPM: NS MSP at 0x2002c6e8
SPM: NS reset vector at 0x16c69
SPM: prepare to jump to Non-Secure image.
*** Booting Zephyr OS build v2.1.99-ncs1-2956-g9bab3a84b642  ***
NAT-test client started
Version: 0.0.0-development
Setting up LTE connection


uart:~$ [00:00:00.208,038] <dbg> lte_lc.lte_lc_system_mode_set: Sending AT command to set system mode: AT%XSYSTEMMODE=1,0,0,0
uart:~$ 

```

**Comment by boundlesscalm** [comment]
Rebuilt from scratch. Hope that fixes it as it worked fine for me.
Looks like your SIM isn't getting an LTE link though.
[merged.zip](https://github.com/NordicSemiconductor/NAT-TestFirmware/files/4786345/merged.zip)

**Comment by coderbyheart** [comment]
Yes, it took a while to connect, there was no status so I assumed it was hanging.

**Review by coderbyheart — APPROVED** [review]
I did a functional test, no source code review.
LEDs behave as documented.

**Review by jhn-nordic — APPROVED** [review]

**Pull request merged**
